eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/,http://localhost:8761/eureka/
  server:
    enable-self-preservation: false
server:
  port: 8760
